# +--------------+
# |  RDSCommons  |
# |    Config    |
# +--------------+

# Do not touch!
CONFIG_VERSION: 12
PLAYER_DATA_VERSION: 7

# Determines the Locale to use for plugin messages
# Currently supports: en-US
# Defaults: en-US
LOCALE: en-US

# Determines whether the plugin will automatically update
# Defaults: false
AUTO_UPDATE: false
# Determines the branch to use for the auto updater
# release: Release versions, such as 0.2.2.1, 0.2.2.2, 0.2.2.3
# snapshot: Snapshot versions, such as 0.2.2.3-SNAPSHOT-1, 0.2.2.3, 0.4.0.0-snapshot-24w14a
# Defaults: release
UPDATE_BRANCH: release
# Determines whether experimental features are enabled
# Defaults: false
EXPERIMENTAL_FEATURES: false
# Determines whether or not event messages are logged
# Defaults: false
DEBUG_EVENTS: false
# Defines the amount of information being outputted
# 0 provides a basic overview of the event
# 1 provides the basic overview along with the most important event data
# 2 provides the basic overview along with all event data
# Defaults: 0
DEBUG_EVENTS_LEVEL: 0